name: Sync to Secondary Repo

on:
  push:
    branches:
      - main  # Change this to "master" if your default branch is named master

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Destination Repo
        uses: wei/git-sync@v3
        with:
          source_repo: "ursilapradeep/UrsilaPradeep"
          source_branch: "refs/heads/*"
          destination_repo: "https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/Ursilasuraj/ursilasuraj.git"
          destination_branch: "refs/heads/*"
